name: mutation test

on:
  pull_request:
    paths: &paths
      - '.github/workflows/mutation.yml'
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    uses: yiisoft/actions/.github/workflows/roave-infection.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.3']
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
